AttributeData:  ; Level One Atrributes
.byte $ff,$aa,$aa,$aa,$9a,$00,$00,$00   ;23C0
.byte $ff,$aa,$aa,$aa,$5a,$00,$00,$00   ;23C1
.byte $ff,$aa,$aa,$aa,$5a,$00,$00,$00   ;23C2
.byte $ff,$aa,$aa,$6a,$a6,$00,$00,$00   ;23C3
.byte $ff,$aa,$aa,$9a,$59,$00,$00,$00   ;23C4
.byte $ff,$aa,$aa,$aa,$5a,$00,$00,$00   ;23C5
.byte $ff,$aa,$aa,$aa,$9a,$00,$00,$00   ;23C6
.byte $ff,$aa,$aa,$aa,$5a,$00,$00,$00   ;23C7

.byte $ff,$aa,$aa,$5a,$9a,$00,$00,$00   ;23C8
.byte $ff,$aa,$aa,$9a,$5a,$00,$00,$00   ;23C9
.byte $ff,$aa,$aa,$aa,$5a,$00,$00,$00   ;23CA
.byte $ff,$aa,$aa,$6a,$56,$00,$00,$00   ;23CB
.byte $ff,$aa,$aa,$9a,$59,$00,$00,$00   ;23CD
.byte $ff,$aa,$aa,$aa,$5a,$00,$00,$00   ;23CE
.byte $ff,$aa,$aa,$aa,$5a,$00,$00,$00   ;23CF
.byte $ff,$aa,$aa,$aa,$5a,$00,$00,$00   ;23D0

.byte $ff,$aa,$aa,$aa,$9a,$00,$00,$00   ;23D1
.byte $ff,$aa,$aa,$aa,$5a,$00,$00,$00   ;23D2
.byte $ff,$aa,$aa,$aa,$5a,$00,$00,$00   ;23D3
.byte $ff,$aa,$aa,$aa,$aa,$00,$00,$00   ;23D4
.byte $ff,$aa,$aa,$aa,$56,$00,$00,$00   ;23D5
.byte $ff,$aa,$aa,$aa,$9a,$00,$00,$00   ;23D6
.byte $ff,$aa,$aa,$aa,$59,$00,$00,$00   ;23D7
.byte $ff,$aa,$aa,$aa,$5a,$00,$00,$00   ;23D8

.byte $ff,$aa,$aa,$aa,$9a,$00,$00,$00   ;23D9
.byte $ff,$aa,$aa,$aa,$5a,$00,$00,$00   ;23DA
.byte $ff,$aa,$aa,$aa,$5a,$00,$00,$00   ;23DB
.byte $ff,$aa,$aa,$aa,$59,$00,$00,$00   ;23DC
.byte $ff,$aa,$aa,$aa,$56,$00,$00,$00   ;23DD
.byte $ff,$aa,$aa,$aa,$5a,$00,$00,$00   ;23DE
.byte $ff,$aa,$aa,$aa,$59,$00,$00,$00   ;23DF
.byte $ff,$aa,$aa,$aa,$5a,$00,$00,$00   ;23E0